@startuml MTProto_Secret_Chat

skinparam Monochrome true
skinparam Shadowing false

participant a as "Client A"
participant s as "Server"
participant b as "Client B"

note over a
Conosce la chiave $k_a$
end note

note over s
Conosce le chiavi $k_a, k_b$
end note

note over b
Conosce la chiave $k_b$
end note

a -> s ++ : ${getDHconfig()}k_a$
a <- s -- : ${g, p}k_a$

note over a
Genera $a \in \mathbb{Z}_p$ e $id$
Calcola $g_a = g^a \mod p$
end note

a -> s ++ : ${id, B, g_a}k_a$
s -> b ++ : ${id, A, B, g_a}k_b$
s <- b ++: ${chatAccepted()}k_b$
s -> b -- :  ${g, p}k_b$

note over b
Genera $b \in \mathbb{Z}_p$ e $id$
Calcola $g_b = g^b \mod p, k = g_a^b$
end note

s <- b -- : ${id, g_b, \mathcal{H}(k)}k_b$
a <- s -- : ${id, B, g_b, \mathcal{H}(k)}k_a$


note over a
Calcola $k = g_b^a$
Controlla $\mathcal{H}(k)$
end note

@enduml